# Generated by Django 4.2.29 on 2026-03-20 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('preacher', models.CharField(blank=True, max_length=100)),
                ('sermon_date', models.DateField()),
                ('youtube_url', models.URLField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('bible_passage', models.CharField(blank=True, max_length=255)),
                ('ai_generated', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-sermon_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_group', models.CharField(blank=True, max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SermonSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_line1', models.CharField(blank=True, max_length=255)),
                ('summary_line2', models.CharField(blank=True, max_length=255)),
                ('summary_line3', models.CharField(blank=True, max_length=255)),
                ('key_point1', models.CharField(blank=True, max_length=255)),
                ('key_point2', models.CharField(blank=True, max_length=255)),
                ('key_point3', models.CharField(blank=True, max_length=255)),
                ('ai_generated', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sermon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='core.sermon')),
            ],
        ),
        migrations.CreateModel(
            name='SermonQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('choice1', models.CharField(max_length=255)),
                ('choice2', models.CharField(max_length=255)),
                ('choice3', models.CharField(max_length=255)),
                ('choice4', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('explanation', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('ai_generated', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='core.sermon')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SermonMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('ai_generated', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='core.sermon')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(blank=True, max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sermonquiz')),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sermon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sermonmission')),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sermon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at', '-id'],
            },
        ),
    ]
