# Generated by Django 4.2.29 on 2026-03-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_weeklychallenge_pointledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='ai_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='import_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='last_ai_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='last_imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
