# Generated by Django 5.2.12 on 2026-03-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sermon_ai_error_sermon_import_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermonsummary',
            name='outline_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sermonsummary',
            name='overview',
            field=models.TextField(blank=True),
        ),
    ]
