# Generated by Django 5.2.12 on 2026-03-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sermonsummary_outline_points_sermonsummary_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermonsummary',
            name='key_point1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sermonsummary',
            name='key_point2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sermonsummary',
            name='key_point3',
            field=models.TextField(blank=True),
        ),
    ]
