# Generated by Django 5.2.12 on 2026-03-21 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sermonsummary_key_point1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('intro', models.TextField(blank=True)),
                ('quiz_question', models.CharField(max_length=255)),
                ('quiz_choice1', models.CharField(max_length=255)),
                ('quiz_choice2', models.CharField(max_length=255)),
                ('quiz_choice3', models.CharField(max_length=255)),
                ('quiz_choice4', models.CharField(max_length=255)),
                ('quiz_answer', models.CharField(max_length=255)),
                ('quiz_explanation', models.TextField(blank=True)),
                ('reflection_question', models.TextField()),
                ('mission_title', models.CharField(max_length=255)),
                ('mission_description', models.TextField(blank=True)),
                ('ai_generated', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_engagements', to='core.weeklychallenge')),
            ],
            options={
                'ordering': ['day_number', 'id'],
                'constraints': [models.UniqueConstraint(fields=('challenge', 'day_number'), name='unique_daily_engagement_per_challenge_day')],
            },
        ),
    ]
