# Generated by Django 5.2.12 on 2026-03-21 04:45

import django.db.models.deletion
from django.db import migrations, models


def backfill_daily_engagement_sermon(apps, schema_editor):
    DailyEngagement = apps.get_model("core", "DailyEngagement")
    for item in DailyEngagement.objects.select_related("challenge__sermon").all():
        if item.challenge_id and item.sermon_id is None:
            item.sermon_id = item.challenge.sermon_id
            item.save(update_fields=["sermon"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dailyengagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyengagement',
            name='sermon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_engagements', to='core.sermon'),
        ),
        migrations.RunPython(backfill_daily_engagement_sermon, noop_reverse),
    ]
