# Generated by Django 5.2.12 on 2026-03-24 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dailyengagement_sermon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointledger',
            name='source',
            field=models.CharField(choices=[('summary', 'Summary Read'), ('quiz', 'Quiz Correct'), ('reflection', 'Reflection Response'), ('mission', 'Mission Completion'), ('daily_bonus', 'Daily Completion Bonus'), ('weekly_bonus', 'Weekly Completion Bonus')], max_length=20),
        ),
        migrations.CreateModel(
            name='DailyMissionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.weeklychallenge')),
                ('daily_engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_completions', to='core.dailyengagement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'daily_engagement'), name='unique_daily_mission_completion_per_user')],
            },
        ),
        migrations.CreateModel(
            name='DailyQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.weeklychallenge')),
                ('daily_engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='core.dailyengagement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'daily_engagement'), name='unique_daily_quiz_attempt_per_user')],
            },
        ),
        migrations.CreateModel(
            name='DailyReflectionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.weeklychallenge')),
                ('daily_engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_responses', to='core.dailyengagement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'daily_engagement'), name='unique_daily_reflection_per_user')],
            },
        ),
    ]
