# Generated by Django 5.2.12 on 2026-03-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pointledger_source_dailymissioncompletion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='church_group',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='member_role',
            field=models.CharField(choices=[('member', '교인'), ('deacon', '집사'), ('kwonsa', '권사'), ('elder', '장로'), ('other', '기타')], default='member', max_length=20),
        ),
    ]
