# Generated by Django 5.2.12 on 2026-03-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_userprofile_church_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='member_role',
            field=models.CharField(choices=[('pastor', '목회자'), ('member', '교인'), ('deacon', '집사'), ('kwonsa', '권사'), ('elder', '장로'), ('other', '기타')], default='member', max_length=20),
        ),
    ]
