# Generated by Django 5.2.12 on 2026-04-08 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_sermon_playback_video_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SermonHighlightChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_choices', to='core.sermon')),
            ],
            options={
                'verbose_name': '설교 인상 문장',
                'verbose_name_plural': '설교 인상 문장',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SermonHighlightVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.sermonhighlightchoice')),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_votes', to='core.sermon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-voted_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'sermon'), name='unique_sermon_highlight_vote_per_user')],
            },
        ),
    ]
