# Generated by Django 5.2.12 on 2026-04-17 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sermonhighlightchoice_sermonhighlightvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='audio_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='last_audio_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SermonAudioClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('weekly_summary', '주간 요약 듣기'), ('daily_content', '오늘 내용 듣기')], max_length=30)),
                ('day_number', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('script', models.TextField(blank=True)),
                ('voice', models.CharField(blank=True, max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='sermons/audio/generated/')),
                ('error', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_clips', to='core.sermon')),
            ],
            options={
                'ordering': ['kind', 'day_number', 'id'],
                'constraints': [models.UniqueConstraint(fields=('sermon', 'kind', 'day_number'), name='unique_sermon_audio_clip_per_kind_day')],
            },
        ),
    ]
