# Generated by Django 5.2.12 on 2026-05-16 05:09

from django.db import migrations, models


def sync_existing_visibility(apps, schema_editor):
    PrayerRequest = apps.get_model("core", "PrayerRequest")
    PrayerRequest.objects.filter(is_public=True).update(visibility="public")
    PrayerRequest.objects.filter(is_public=False).update(visibility="private")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_prayerrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="prayerrequest",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "혼자 기도할게요"),
                    ("public", "함께 기도 부탁드려요"),
                    ("anonymous", "이름은 숨기고 함께 기도 부탁드려요"),
                ],
                default="private",
                max_length=20,
            ),
        ),
        migrations.RunPython(sync_existing_visibility, noop_reverse),
    ]
