# Generated by Django 5.2.12 on 2026-05-20 22:23

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_transcriptcorrectionrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcriptcorrectionrule',
            options={'ordering': ['sort_order', 'source_text', 'id'], 'verbose_name': 'AI 단어 학습 시키기', 'verbose_name_plural': 'AI 단어 학습 시키기'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_use_audio_transcriber',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PastorAudioTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(upload_to=core.models.pastor_audio_transcript_upload_to)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('source_content_type', models.CharField(blank=True, max_length=120)),
                ('source_size', models.PositiveBigIntegerField(default=0)),
                ('transcript_text', models.TextField(blank=True)),
                ('error_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('completed', '완료'), ('failed', '실패')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pastor_audio_transcripts', to='core.church')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastor_audio_transcripts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '목회자 음성 전사',
                'verbose_name_plural': '목회자 음성 전사',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
