# Generated by Django 5.2.12 on 2026-09-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_userprofile_reminders_webpushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='pastor_review_email_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='pastor_review_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
