from django.urls import path
from django.contrib.auth.views import PasswordChangeDoneView, PasswordChangeView

from .views import (
    complete_mission_view,
    create_prayer_request_view,
    delete_pastor_audio_transcript_view,
    delete_prayer_request_view,
    email_pastor_audio_transcript_view,
    home_view,
    join_prayer_request_view,
    login_view,
    logout_view,
    my_history_view,
    pastor_audio_transcriber_view,
    pastor_audio_transcriber_record_view,
    pastor_dashboard_view,
    pastor_members_view,
    pastor_reports_view,
    pastor_sermon_edit_view,
    pastor_transcript_corrections_view,
    read_sermon_view,
    signup_view,
    submit_highlight_vote_view,
    submit_daily_quiz_view,
    submit_reflection_view,
    transcribe_voice_note_view,
    update_prayer_request_view,
    watch_sermon_view,
)

app_name = "core"

urlpatterns = [
    path("", home_view, name="home"),
    path("history/", my_history_view, name="my_history"),
    path("pastor/", pastor_dashboard_view, name="pastor_dashboard"),
    path("pastor/audio-transcripts/", pastor_audio_transcriber_view, name="pastor_audio_transcriber"),
    path("pastor/audio-transcripts/record/", pastor_audio_transcriber_record_view, name="pastor_audio_transcriber_record"),
    path("pastor/audio-transcripts/<int:pk>/delete/", delete_pastor_audio_transcript_view, name="delete_pastor_audio_transcript"),
    path("pastor/audio-transcripts/<int:pk>/email/", email_pastor_audio_transcript_view, name="email_pastor_audio_transcript"),
    path("pastor/reports/", pastor_reports_view, name="pastor_reports"),
    path("pastor/members/", pastor_members_view, name="pastor_members"),
    path("pastor/ai-words/", pastor_transcript_corrections_view, name="pastor_transcript_corrections"),
    path("pastor/sermons/<int:pk>/", pastor_sermon_edit_view, name="pastor_sermon_edit"),
    path("watch/", watch_sermon_view, name="watch_sermon"),
    path("read/", read_sermon_view, name="read_sermon"),
    path("login/", login_view, name="login"),
    path("signup/", signup_view, name="signup"),
    path("logout/", logout_view, name="logout"),
    path(
        "password-change/",
        PasswordChangeView.as_view(
            template_name="core/password_change.html",
            success_url="/password-change/done/",
        ),
        name="password_change",
    ),
    path(
        "password-change/done/",
        PasswordChangeDoneView.as_view(template_name="core/password_change_done.html"),
        name="password_change_done",
    ),
    path("daily/<int:pk>/quiz/", submit_daily_quiz_view, name="submit_daily_quiz"),
    path("daily/<int:pk>/reflection/", submit_reflection_view, name="submit_reflection"),
    path("daily/<int:pk>/mission/", complete_mission_view, name="complete_mission"),
    path("prayers/create/", create_prayer_request_view, name="create_prayer_request"),
    path("prayers/<int:pk>/join/", join_prayer_request_view, name="join_prayer_request"),
    path("prayers/<int:pk>/update/", update_prayer_request_view, name="update_prayer_request"),
    path("prayers/<int:pk>/delete/", delete_prayer_request_view, name="delete_prayer_request"),
    path("voice/transcribe/", transcribe_voice_note_view, name="transcribe_voice_note"),
    path("highlight/vote/", submit_highlight_vote_view, name="submit_highlight_vote"),
    path("<slug:church_slug>/", home_view, name="church_home"),
    path("<slug:church_slug>/history/", my_history_view, name="church_my_history"),
    path("<slug:church_slug>/watch/", watch_sermon_view, name="church_watch_sermon"),
    path("<slug:church_slug>/read/", read_sermon_view, name="church_read_sermon"),
    path("<slug:church_slug>/login/", login_view, name="church_login"),
    path("<slug:church_slug>/signup/", signup_view, name="church_signup"),
    path("<slug:church_slug>/logout/", logout_view, name="church_logout"),
]
